name: RDP with ngrok
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1 -Force

      - name: Create RDP User
        run: |
          $password = "A@405060"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (-not (Get-LocalUser -Name "ASEEL5" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "ASEEL5" -Password $securePass -AccountNeverExpires
          }
          Add-LocalGroupMember -Group "Administrators" -Member "ASEEL5"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "ASEEL5"
          echo "RDP User: ASEEL5"
          echo "RDP Password: $password"

      - name: Download and Setup ngrok
        run: |
          $workDir = $env:GITHUB_WORKSPACE
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "$workDir\ngrok.zip"
          Expand-Archive -Path "$workDir\ngrok.zip" -DestinationPath "$workDir"
          Move-Item -Path "$workDir\ngrok.exe" -Destination "C:\Windows\System32\"

      - name: Establish ngrok Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # إضافة رمز المصادقة إلى ملف الإعدادات لضمان تطبيقه
          ngrok config add-authtoken $env:NGROK_AUTH_TOKEN
          # تشغيل النفق في الخلفية وتسجيل المخرجات
          Start-Process -FilePath "ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow -RedirectStandardOutput "ngrok.log"

      - name: Display RDP Connection Info
        run: |
          # الانتظار لفترة أطول قليلاً لضمان بدء ngrok
          Start-Sleep -s 15
          Write-Host "--- Displaying ngrok logs for debugging ---"
          # عرض محتويات ملف السجل بالكامل لتصحيح الأخطاء
          if (Test-Path ngrok.log ) {
            Get-Content ngrok.log
          } else {
            Write-Warning "ngrok.log file not found."
          }
          Write-Host "-------------------------------------------"
          
          # محاولة استخراج العنوان
          $tcp_address = (Get-Content ngrok.log | Select-String "url=tcp://(.+)" | ForEach-Object { $_.Matches.Groups[1].Value })
          
          if ($tcp_address) {
            Write-Host "`n=== RDP ACCESS ==="
            Write-Host "Address: $tcp_address"
            Write-Host "Username: ASEEL5"
            Write-Host "Password: A@405060"
            Write-Host "==================`n"
          } else {
            Write-Error "Failed to get ngrok TCP address. Please check the logs above."
            exit 1
          }
          
      - name: Maintain Connection
        run: |
          # حلقة لا نهائية للحفاظ على تشغيل المهمة
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - To terminate, cancel the workflow run on GitHub."
              Start-Sleep -Seconds 300
          }
